// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.2.0
//      Runtime Version:2.0.50727.5444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace PairTracker.IntegrationTests.Specifications
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Calculate Session Length")]
    public partial class CalculateSessionLengthFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CalculateSessionLength.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Calculate Session Length", "In order to asses how well I am pairing\r\nAs a programmer\r\nI want the system to ca" +
                    "lculate the length of the session", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No Activity for 10 seconds")]
        public virtual void NoActivityFor10Seconds()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No Activity for 10 seconds", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("a new session has been started");
#line 8
testRunner.And("10 seconds elapses");
#line 9
testRunner.When("the session is stopped");
#line 10
testRunner.Then("the session length is 10 seconds");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 programmers each control for 5 seconds")]
        public virtual void _2ProgrammersEachControlFor5Seconds()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 programmers each control for 5 seconds", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
testRunner.Given("a new session has been started");
#line 14
testRunner.And("Programmer 1 takes control");
#line 15
testRunner.And("5 seconds elapses");
#line 16
testRunner.And("Programmer 2 takes control");
#line 17
testRunner.And("5 seconds elapses");
#line 18
testRunner.When("the session is stopped");
#line 19
testRunner.Then("the session length is 10 seconds");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 programmers each control for 5 seconds with a 5 second pause in between")]
        public virtual void _2ProgrammersEachControlFor5SecondsWithA5SecondPauseInBetween()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 programmers each control for 5 seconds with a 5 second pause in between", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
testRunner.Given("a new session has been started");
#line 23
testRunner.And("Programmer 1 takes control");
#line 24
testRunner.And("5 seconds elapses");
#line 25
testRunner.And("the session is paused");
#line 26
testRunner.And("5 seconds elapses");
#line 27
testRunner.And("the session is resumed");
#line 28
testRunner.And("Programmer 2 takes control");
#line 29
testRunner.And("5 seconds elapses");
#line 30
testRunner.When("the session is stopped");
#line 31
testRunner.Then("the session length is 10 seconds");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
